version: "3.7"
services:

  db:
    image: mysql
    container_name: toko_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superUseR_passw0rd
      MYSQL_DATABASE: toko_db
      MYSQL_USER: toko_app_user
      MYSQL_PASSWORD: passw0rd

  storage:
    image: minio/minio
    container_name: toko_storage
    volumes:
      - toko-image-data-1:/image-data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    command: server /image-data

volumes:
  toko-image-data-1:
    name: toko-image-data-volume
