version: "3.7"
services:

  test_db:
    image: postgres
    container_name: toko_test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
