version: "3.7"
services:

  test_db:
    image: mysql
    container_name: toko_test_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
