spring:
  datasource:
    url: jdbc:mysql://${AWS_RDS_URL}:3306/toko_db
    username: ${AWS_RDS_USER}
    password: ${AWS_RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
storage:
  endpoint: https://toko-images-dev.s3.amazonaws.com
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: toko-images-dev
