---
swagger: "2.0"
info:
  description: "Toko REST API methods description"
  version: "0.0.1"
  title: "Toko REST API"
  contact:
    email: "dauren.del@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.toko.kz"
basePath: "/v1"
tags:
  - name: "products"
    description: "Product API to manage user's product catalog"
  - name: "Users"
    description: "Operations about user"

paths:
  # Products API
  "/products":
    get:
      tags:
        - "products"
      summary: "Retrieve all products"
      operationId: "getProducts"
      produces:
        - "application/json"
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /user:
    post:
      tags:
        - "Users"
      summary: "Create user"
      description: "This method creates a new user."
      operationId: "createUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Create user request"
          required: true
          schema:
            $ref: "#/definitions/CreateUserRequest"
      responses:
        default:
          description: "successful operation"

definitions:
  Product:
     type: object
     properties:
       id:
         type: integer
         format: int64
       imageLink:
         type: string
         format: uri
       name:
         type: string
       price:
         type: number
         format: double
  CreateUserRequest:
    type: object
    properties:
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password
      phone:
        type: string
