openapi: 3.0.1
info:
  title: Toko REST API
  description: Toko REST API methods description
  contact:
    email: dauren.del@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://api.toko.kz/v1
tags:
  - name: Products
    description: Product API to manage user's product catalog
  - name: Users
    description: Operations about user
paths:
  /products:
    get:
      tags:
        - Products
      summary: Retrieve all products
      operationId: getProducts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        imageLink:
          type: string
          format: uri
        name:
          type: string
        price:
          type: number
          format: double
