# This workflow will deploy a Java app (.jar file) to AWS Elastic Beanstalk
#

name: Deployment to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy:
    name: Deploy to AWS Elastic Beanstalk

    runs-on: ubuntu-latest

    steps:
      - name: Display AWS CLI version
        run: |
          aws --version
      - name: Add config file
        run: |
          cd ~
          mkdir .aws
          echo "[default]" >> config
          echo "region=us-east-1" >> config
          cat ~/.aws/config
      - name: Add credentials file
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          cd ~
          mkdir .aws
          echo "[default]" >> credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY}" >> credentials
          echo "aws_secret_access_key=${AWS_SECRET_KEY}" >> credentials
      - name: Display AWS CLI confgiuration
        run: |
          aws configure list
