# This workflow will create a new version tag in master branch

name: Creating a tag

on:
  push:
    branches: [ master ]

jobs:
  tagging:
    name: Creating a new tag

    runs-on: ubuntu-latest

    outputs:
      app-version: ${{ steps.get-app-version.outputs.app-version }}
      tag-version: ${{ steps.get-tag-version.outputs.tag-version }}
      tag-annotation: ${{ steps.get-tag-annotation.outputs.tag-annotation }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the current app version
        id: get-app-version
        run: |
          version="v$(./gradlew version -q)"
          echo $version
          echo "::set-output name=app-version::$version"

      - name: Get the latest tag version
        id: get-tag-version
        run: |
          version="$(git describe --tags --abbrev=0)"
          echo $version
          echo "::set-output name=tag-version::$version"

      #- name: Prepare tag annotation from Git Log
      #  id: get-tag-annotation
      #  env:
      #    TAG_VERSION: ${{ needs.tagging.outputs.tag-version }}
      #  run: |
      #    echo $TAG_VERSION
      #    git log v0.2.1..origin --pretty=format:'-%s'
      #    annotation="$(git log v0.2.1..origin --pretty=format:'-%s')"
      #    echo $annotation
      #    echo "::set-output name=tag-annotation::$annotation"
      
      - name: Echo env vars
        id: echo-env-var
        env:
          APP_VERSION: ${{ needs.tagging.outputs.app-version }}
          TAG_VERSION: ${{ needs.tagging.outputs.tag-version }}
        run: |
          echo "start"
          echo ">$APP_VERSION<"
          echo ">$TAG_VERSION<"
          echo "end"

      - name: Create a new tag
        id: create-new-tag
        env:
          APP_VERSION: ${{ needs.tagging.outputs.app-version }}
          TAG_VERSION: ${{ needs.tagging.outputs.tag-version }}
        if: ${{ env.APP_VERSION != env.TAG_VERSION }}
        run: |
          git tag -a $APP_VERSION -m "Tag for version $APP_VERSION"

      - name: Push the tag
        id: push-tag
        run: |
          git push origin tags
